# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59b16d0d8f307c30a46a6c7de1ea807078c691e71ef002542b498250a2a435cd87b9f214ae434e459efe05c64a0a660744beabfe200e9cb317e84b0f54dd6670

test:
  secret_key_base: 4d08327cf8c66bf8615fe2bd746f2b73a8d0dc8c4f4edaa763b32615ed229f24782a537468cf67b996e99eb0efdef9c0231a7e2d30fdb38f85a9e6f0c2579877

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
